config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: %i[edit update show], param: :username do
    member do
      delete :delete_avatar
      patch :update_avatar
    end
  end

  resource :password_reset, only: %i[new create edit update]

  resources :posts do
    resources :comments, only: %i[create destroy]
  end

  namespace :api do
    resources :tags, only: :index
  end

  # Defines the root path route ("/")
  root 'posts#index'
end

app/models/user.rb
class User < ApplicationRecord
  before_create :generate_random_username

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :posts, dependent: :destroy
  has_one_attached :avatar
  has_one_attached :avatar_resized

  validates :avatar, blob: { content_type: :image } # supported options: :web_image, :image, :audio, :video, :text
  validates :username, uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 },
                       presence: true,
                       if: -> { persisted? && username_changed? }

  def author?(obj)
    obj.user == self
  end

  def guest?
    false
  end

  def resize_avatar
    image = MiniMagick::Image.read(avatar.download)
    image.resize '400x400'
    filename = "avatar_resized_#{SecureRandom.uuid}.jpg"
    path = Rails.root.join('tmp', filename)
    image.write(path)

    avatar_resized.attach(
      io: File.open(path),
      filename: filename,
      content_type: 'image/jpeg'
    )

    File.delete(path)
  end

  private

  def generate_random_username
    self.username = "user#{SecureRandom.hex(6)}"
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  private

  def set_user
    @user = User.find_by(username: params[:username])
    redirect_to root_path, alert: 'User not found.' unless @user
  end

  def after_update_path_for(resource)
    user_path(resource.username)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email username password password_confirmation])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[email username password password_confirmation])
  end

  # # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end
  #
  # # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_authentication, only: [:edit]
  before_action :set_user_by_username, only: %i[show update_avatar delete_avatar]
  before_action :set_user!, only: %i[edit]

  def show
    @pagy, @posts = pagy @user.posts.order(created_at: :desc)
    @posts = @posts.decorate
  end

  def edit; end

  def update_avatar
    if params[:user].blank? || params[:user][:avatar].blank?
      flash.now[:error] = 'No image present.'
    elsif @user.update user_params
      respond_to do |format|
        format.html do
          @user.avatar.attach(params[:user][:avatar])
          @user.resize_avatar
          flash[:success] = 'Avatar updated!'
          redirect_to edit_user_registration_path(current_user.username)
        end

        format.turbo_stream do
          @user.avatar.attach(params[:user][:avatar])
          @user.resize_avatar
          flash.now[:success] = 'Avatar was successfully updated!'
          render :update
        end
      end
    else
      flash.now[:error] = 'Failed to update user.'
    end
  end

  def delete_avatar
    @user.avatar.purge
    @user.avatar_resized.purge
    redirect_to edit_user_registration_path(current_user.username)
    flash[:success] = 'Avatar was successfully deleted!'
  end

  private

  def set_user_by_username
    @user = User.find_by!(username: params[:username])
  end

  def set_user!
    @user = User.find params[:username]
  end

  def user_params
    params.require(:user).permit(:email, :username, :password, :avatar, :avatar_resized)
  end
end

app/views/users/_user_card.html.erb
<%= turbo_frame_tag 'user-card' do %>
  <div class="card custom-user-card" id="<%= dom_id(@user) %>">
    <div class="row">
      <div class="col-md-5">
        <% if @user.avatar_resized.attached? %>
          <%= link_to @user.avatar, data: { turbo: false, toggle: 'lightbox'} do %>
            <% image_tag(@user.avatar_resized, class: 'user-avatar mb-2') %>
          <% end%>
        <% else %>
          <%= link_to "/images/default_avatar.jpg", data: { turbo: false, toggle: 'lightbox'} do %>
            <% image_tag("/images/default_avatar.jpg", class: 'user-avatar mb-2') %>
          <% end %>
        <% end %>

        <div class="d-flex align-items-center">
          <% if local_assigns[:editable] && editable %>
            <%= form_with model: @user, url: update_avatar_user_path(@user.username), method: :patch,
            data: { turbo_frame: 'user-card' } do |form| %>
              <%= form.file_field :avatar, class: 'form-control mb-2' %>
              <%= form.submit "Upload Avatar", class: 'btn btn-primary' %>

              <% if @user.avatar_resized.attached? %>
                <button type="button" class="btn btn-danger mb-0" 
                onclick="deleteAvatar('<%= delete_avatar_user_path(current_user.username) %>')">
                  Delete Avatar
                </button>
              <% end %>
            <% end %>
         <% end %>
        </div>
      </div>

      <div class="col-md-7">
        <h2><%= @user.username %> </h2>
      </div>
    </div>
  </div>
<% end %>

app/views/users/destroy.turbo_stream.erb
<%= turbo_stream.replace dom_id(@user) do %>
  <%= render 'user_card', user: @user, editable: true %>
<% end %>

<%= prepend_flash %>

app/views/users/show.html.erb
<div class="container">
  <%= turbo_frame_tag 'user-card' do %>
     <%= render 'user_card', user: @user, editable: false %>
  <% end %>

  <br>

  <div class="row">
    <h2>Last posts by <%= @user.username %>:</h2>

    <%= render @posts %>

    <div class="d-flex justify-content-center my-3">
      <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
    </div>
  </div>
</div>

app/views/users/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@user) do %>
  <%= render 'user_card', user: @user, editable: true %>
<% end %>

<%= prepend_flash %>