config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: %i[edit update show], param: :username do
    member do
      delete :delete_avatar
      patch :update_avatar
    end
  end

  resource :password_reset, only: %i[new create edit update]

  resources :posts do
    resources :comments, only: %i[create destroy]
  end

  namespace :api do
    resources :tags, only: :index
  end

  # Defines the root path route ("/")
  root 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
  include Authorship
  include Commentable

  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  validates :body, presence: true, length: { minimum: 1, maximum: 2000 }

  belongs_to :user

  scope :all_by_tags, lambda { |tags|
    posts = includes(:user)
    posts = if tags
              posts.joins(:tags).where(tags: tags).preload(:tags)
            else
              posts.includes(:post_tags, :tags)
            end

    posts.order(created_at: :desc)
  }
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :require_authentication, except: %i[index show]
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authorize_post!
  after_action :verify_authorized
  before_action :fetch_tags, only: %i[new edit]

  def index
    @pagy, @posts = pagy Post.all_by_tags(params[:tag_ids])
    @posts = @posts.decorate
    @tag = Tag.find_by(id: params[:tag_ids])
  end

  def new
    @post = Post.new
  end

  def edit; end

  def show
    @post = Post.find(params[:id])
    @post = @post.decorate
  end

  def create
    @post = current_user.posts.build post_params

    if @post.save
      respond_to do |format|
        format.html do
          flash[:success] = 'Post created!'
          redirect_to posts_path
        end

        format.turbo_stream do
          @post = @post.decorate
          flash.now[:success] = 'Post created!'
        end
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update post_params
      respond_to do |format|
        format.html do
          flash[:success] = 'Post updated!'
          redirect_to posts_path
        end

        format.turbo_stream do
          @post = @post.decorate
          flash.now[:success] = 'Post updated!'
        end
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html do
        flash[:success] = 'Post deleted!'
        redirect_to posts_path
      end

      format.turbo_stream do
        flash[:success] = 'Post deleted!'
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:body, tag_ids: [])
  end

  def set_post
    @post = Post.find params[:id]
  end

  def authorize_post!
    authorize(@post || Post)
  end

  def fetch_tags
    @tags = Tag.all
  end
end

app/views/posts/_form.html.erb
<%= turbo_frame_tag @post do %>
  <%= form_with model: @post do |f| %>
    <%= render 'shared/errors', object: @post %>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :body %>
      </div>

      <div class="col-sm-10">
        <%= f.text_area :body, class: 'form-control' %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :tags %>
      </div>

      <div class="col-sm-10">
        <%= f.collection_select :tag_ids, (@tags || []), :id, :title, {}, multiple: true,
                                class: 'js-multiple-select',
                                data: {
                                  'controller': 'tom-select',
                                  'tom_select_ajax_url_value': '/api/tags'
                                } %>
      </div>
    </div>

    <%= f.submit "Submit", class: 'btn btn-primary mb-2' %>
  <% end %>
<% end %>

app/views/posts/_post.html.erb
<%= turbo_frame_tag post do %>
  <div class="card custom-card mb-3">
    <div class="row">
      <div class="col-sm-2">
        <% if post.user.avatar_resized.attached? %>
          <%= image_tag post.user.avatar_resized, class: 'user-avatar-post' %>
        <% else %>
          <%= image_tag "/images/default_avatar100x100.jpg", class: 'user-avatar-post' %>
        <% end %>
      </div>

      <div class="col-sm-10">
        <section class="card-text">
            <h2>
              <%= link_to post.user.username, user_path(post.user.username), class: 'user-link', data: { turbo: false } %>
            </h2>

            <time>
              <small><%= post.formatted_created_at %></small>
            </time>

            <div class="my-2">
              <p>
                <%= sanitize post.body %>
              </p>
            </div>

          <div class="buttons-container">
            <div class="post-left-button">
              <% if policy(post).edit? && params[:action] == 'show' %>
                <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-primary' %>
              <% end %>

              <% if policy(post).destroy? && params[:action] == 'show' %>
                <%= link_to 'Delete', post_path(post), class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
              <% end %>
            </div>

            <% unless params[:action] == 'show' %>
              <div class="post-right-button">
                <%= link_to "#{post.comments.count} comments", post_path(post), class: 'btn btn-primary', data: { turbo: false } %>
              </div>
            <% end %>
          </div>
        </section>
      </div>
    </div>

    <% unless params[:action] == 'show' %>
      <div class="row">
        <div class="col-sm-2">
        </div>
        <div class="col-sm-10">
          <%= render post.tags %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend 'posts', render(@post) %>
<%= prepend_flash %>

app/views/posts/destroy.turbo_stream.erb
<%= turbo_stream.remove @post %>
<%= prepend_flash %>

app/views/posts/edit.html.erb
<h1>Edit post:</h1>

<%= render 'form', tags: @tags %>

app/views/posts/index.html.erb
<section class="mb-4">
  <h2>Search by tags: </h2>

  <%= form_with url: posts_path, method: :get do |f| %>
      <%= f.collection_select :tag_ids, (@tags || []), :id, :title, {selected: params[:tag_id]},
        multiple: true, required: true,
        class: 'js-multiple-select w-100 mb-2', placeholder: 'Start typing here to find tags',
                              data: {'tom_select_ajax_url_value': '/api/tags',
                                     'controller': 'tom-select'} %>

      <%= f.submit 'Submit', class: 'btn btn-primary' %>
  <% end %>
</section>

<% if params[:tag_ids].present? %>
  <h3>Posts with tag:  <span class="badge rounded-pill bg-secondary d-inline-block px-2 pt-1 me-1 text-decoration-none">
      <%= @tag.title %>
    </span></h3>
<% else %>
  <h3>All posts:</h3>

  <% if current_user.present? %>
    <%= link_to 'New post', new_post_path, class: 'btn btn-primary btn-sm mb-3',
        data: { turbo_frame: dom_id(Post.new) }%>

    <div class="my-3">
      <%= turbo_frame_tag Post.new %>
    </div>
  <% end %>
<% end %>

<%= turbo_frame_tag 'posts' do %>
  <%= render @posts %>
<% end %>

<div class="d-flex justify-content-center my-3">
  <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
</div>

app/views/posts/new.html.erb
<h1>New post: </h1>

<%= render 'form', tags: @tags %>

app/views/posts/show.html.erb
<%= render @post %>

<% if @post.tags.present? %>
  <div class="row">
    <div class="col-sm-12">
      <%= render @post.tags %>
    </div>
  </div>
<% end %>

<%= render 'comments/commentable', commentable: @post, comment: @comment,
           html_id: 'postComments' %>

app/views/posts/update.turbo_stream.erb
<%= turbo_stream.replace @post, render(@post) %>
<%= prepend_flash %>